learning_users/blog_app/urls.py
# from django.conf.urls import url
from blog_app import views
from django.urls import path

# TEMPLATE TAGGING
app_name = 'blog_app'

urlpatterns = [
    path('', views.index, name='blog_app_index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import include
from blog_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blog_app/', include('blog_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('booking/', views.booking, name='booking')
]

learning_users/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)

    def __str__(self):
        return self.user.username

learning_users/blog_app/forms.py
from django import forms
from django.contrib.auth.models import User
from blog_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_picture')

learning_users/blog_app/views.py
from django.shortcuts import render
from blog_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    context_dict = {"name": 'Hello World'}
    return render(request, 'blog_app/index.html', context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']
            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    # else of request.method
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'blog_app/registration.html',
           {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered})


# views name should not match anything we have imported like login, authenticate etc
def user_login(request):

    if request.method == 'POST':
        filled_username = request.POST.get('username')
        filled_password = request.POST.get('password')

        # builtin automatic authenticate user, and checks login by login() method. Thanks django
        user = authenticate(username=filled_username, password=filled_password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('booking'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE! Contact Admin!")

        else:
            print("Someone tried login and failed!")
            print("Username {} and Password {}", format(filled_username, filled_password))
            return HttpResponse('INVALID CREDENTIALS!')

    else:
        return render(request, 'blog_app/login.html', {})


@login_required   # decorator function checks only logged-in users can log out
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required()
def booking(request):
    # return HttpResponse("You are Logged in. Enjoy!")
    return render(request, 'blog_app/booking.html', {})

learning_users/templates/blog_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">The Lovely Blog</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li>
          <a class="nav-link active" href="{% url 'blog_app:register' %}">Register</a>
        </li>
        <li>
          <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
        </li>

        {% if user.is_authenticated %}
        <li><a class="nav-link active" href="{% url 'logout' %}">Logout {{ user.username }} </a></li>
        {% else %}
        <li><a class="nav-link active" href="{% url 'blog_app:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
</div>

<div class="container">
{% block body_block %}
{% endblock %}
</div>

</body>
</html>

learning_users/templates/blog_app/booking.html
<!doctype html>
{% extends 'blog_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
<h1>Welcome to The Lovely Blog Booking page</h1>
    {% if user.is_authenticated %}
    <h2>Happy Reading! {{ user.username }}</h2>
    {% else %}
    <h2>Login for Free!</h2>
    {% endif %}
</div>
{% endblock %}

learning_users/templates/blog_app/index.html
<!doctype html>
{% extends 'blog_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
<h1>Django Learning User Authentication</h1>
    {{ name }}
    {% if user.is_authenticated %}
    <h2>Happy Reading! {{ user.username }}</h2>
    {% else %}
    <h2>Login for Free!</h2>
    {% endif %}
</div>

{% endblock %}

learning_users/templates/blog_app/login.html
{% extends 'blog_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h2>Please Login!</h2>
    <form action="{% url 'blog_app:user_login' %}" method="POST">
    {% csrf_token %}
        <label for="username"> Username: </label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password"> Password: </label>
        <input type="password" name="password" value="">

        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

learning_users/templates/blog_app/registration.html
<!doctype html>
{% extends 'blog_app/base.html' %}


{% block body_block %}

<div class="jumbotron">
<h1>User Registration! </h1>
    {% if registered %}
     <h2>Thank you for registering! </h2>
    {% else %}
     <h2>Fill out the form to Register!</h2>

    <form method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>

{% endblock %}