ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path, include
from appTwo import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('apptwo/', include('appTwo.urls')),

]

ProTwo/appTwo/urls.py
from django.urls import path
from . import views

#TEMPLATE TAGGING
app_name = 'apptwo'

urlpatterns = [
    path('help/', views.help, name='help'),
    path('users/', views.users, name='users'),
    # path('user_form/', views.user_form_view, name='user_form'),
    path('user_form/', views.users, name='user_form'),

    path('', views.apptwo_index, name='apptwo_index'),
    path('other/', views.other_page, name='other'),
    path('relative/', views.relative_url_templates, name='relative')

]

ProTwo/appTwo/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=264)
    email = models.CharField(max_length=264)
    confirm_email = models.CharField(max_length=264)
    address = models.CharField(max_length=264)


    def __str__(self) -> str:
        return self.user_fname
    

ProTwo/appTwo/forms.py
from django import forms
from django.core import validators
from appTwo.models import Users


def check_for_p(value):
    if value[0].lower() != 'p':
        raise forms.ValidationError('Name must start with "P"')
    
class NewUserForm(forms.ModelForm):
    class Meta:
        model = Users
        # fields = ['name', 'email', 'confirm_email', 'address']
        fields = '__all__'
        
    # name = forms.CharField(validators=[check_for_p])
    # email = forms.EmailField(label='Your Email')
    # confirm_email = forms.EmailField(label='Confirm your Email')
    # address = forms.CharField(widget=forms.Textarea)


    # this is not needed                                                   
    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError('Got a bot')
        return botcatcher
        
# Form with database connect
        

ProTwo/appTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from appTwo.models import Users
from appTwo.forms import NewUserForm
from . import forms

# Create your views here.
def index(request):
    # return HttpResponse("<em>Welcome to Second Project, go to /users</em>")
    index_dict = {'index_insert':'INDEX PAGE'}
    return render(request,'appTwo/index.html',context=index_dict)


def apptwo_index(request):
    index_dict = {'address': 'Company address is two horizon center, Gurgaon', 'employees': 2000}
    return render(request,'appTwo/apptwo_index.html',context=index_dict)

def help(request):
    helpdict = {'help_insert':'HELP PAGE'}
    return render(request,'appTwo/help.html',context=helpdict)

def users(request):
    # users_list = Users.objects.order_by('id')
    # user_dict = {'users': users_list}
    # return render(request, 'appTwo/users.html', context=user_dict)
    
    #creating form by model forms
    form = NewUserForm(request.POST)
    if request.method == 'Post':
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('INVALID FORM')

    return render(request, 'appTwo/user_form.html', {'form':form})        

def user_form_view(request):
    form = forms.NewUserForm()
    if request.method == "POST":
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            print("Validation success!")
            print(form.cleaned_data['name'])
            # print("Name: " + form.changed_data['name'])
            # print("email: " + form.changed_data['email'])
            # print("address: " + form.changed_data['address'])


    return render(request, 'appTwo/user_form.html', {'form': form})

def other_page(request):
    return render(request, 'appTwo/other.html')

def base(request):
    return render(request, 'appTwo/base.html')

def relative_url_templates(request):
    return render(request, 'appTwo/relative_url_templates.html')

ProTwo/appTwo/templates/appTwo/apptwo_index.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load template_filters %}
{% block body_block %}
        <h2>Welcome to Index page of appTwo </h2>
{{ address | cut:'center' }}
<p>Employees: {{ employees | add:"99" }} </p>
{{ address | add_last:'INDIA' }}

{% endblock %}

ProTwo/appTwo/templates/appTwo/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Second Project base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
<div class="container">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Brand Home</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'apptwo:relative' %}">Relative</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'apptwo:other' %}">Other</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'apptwo:apptwo_index' %}">Index</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>

  <div class="container">
      {% block body_block %}
        <!--        Anything outside of this will be inherited if you extend.-->
      {% endblock %}
  </div>
  </body>
</html>

ProTwo/appTwo/templates/appTwo/help.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HELP PAGE</title>
  </head>
  <body>
    {{ help_insert }}

  </body>
</html>

ProTwo/appTwo/templates/appTwo/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Second Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h2>Welcome to Second Project Index Page, go to /users </h2>
        <h2>To Register Go to /user_form </h2>
        {{ index_insert }}
      </div>
    </div>
  </body>
</html>

ProTwo/appTwo/templates/appTwo/other.html
<!doctype html>
{% load my_templates %}
{% extends "appTwo/base.html" %}
{% block body_block %}
    <h2>WELCOME TO OTHER!</h2>
    <h2>Inherited block from base</h2>
{% endblock %}

ProTwo/appTwo/templates/appTwo/relative_url_templates.html
<!doctype html>
{% extends "appTwo/base.html" %}
{% block body_block %}
    <h2>WELCOME TO RELATIVE!</h2>
{% endblock %}

ProTwo/appTwo/templates/appTwo/user_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h2>Fill out the Register Form!</h2>
    <div class="container">
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" name="submit">
        </form>
        

    </div>

  </body>
</html>

ProTwo/appTwo/templates/appTwo/users.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Users AppTwo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Your Users!</h1>
    <div class="users_class">
      {% if users %}
      <table>
        <thead>
          <th>ID</th>
          <th>First Name</th>
          <th>Last name</th>
          <th>User Email</th>
        </thead>
        {% for user in users %}
        <tr>
          <td>{{ user.id}}</td>
          <td>{{ user.user_fname}}</td>
          <td>{{ user.user_lname}}</td>
          <td>{{ user.user_email}}</td>
        </tr>
        {% endfor %}  
      </table>
      {% else %}
      <p> No Users Found!</p>
      {% endif %}
    </div>
  </body>
</html>